### ISSUE TITLE
Review Checklist

### ISSUE THREAD

**Issue by ZachAndrews98** [huangs1/Simple-Dungeon-Game#5]
- [X] Project Name and Description

- [X] How to Build and Run the Project

- [X] How to Test the Application

- [X] Software Tools Used

- [X] Tangible Results

- [X] Travis CI Integration

- [X] Use of Github Flow

- [x] Use of Standard Directory Conventions

- [ ] License

**Comment by huangs1** [comment]
@ZachAndrews98 Thank you for the checklist! I have now added the License for my project!
